### ISSUE TITLE
Ubuntu-20.04 installation issue

### ISSUE THREAD

**Issue by paultheshark** [G-dH/gnome-colorblind-filters#11]
Hi G-dH,
I tried to install this extension on two different Ubuntu-20.04 installations, using both the browser and the github version, but it looks like for some reason the extensions cannot start.

Looking to the information available from the Gnome Looking Glass (ALT+F2, lg) panel, I see reported an error like this:
TypeError: Math.clamp is not a function

Do you have any clue of what is going wrong?
The extension looks working fine on 22.04.

Thanks.

**Comment by G-dH** [comment]
Thanks for reminding me of this issue, I noticed it a few days ago. I used a function that doesn't exist in the version of the js engine that 20.04 GS is running on. I'll fix it today.

**Comment by G-dH** [comment]
GitHub version should be ok now...

**Comment by paultheshark** [comment]
Confirmed, now it is loading and working.
Thanks

**Comment by G-dH** [comment]
Thanks, closing and exporting to e.g.o.
